import Head from 'next/head'
import styles from '../styles/Global.module.css'

import Header from '../components/Header'

export default function Home() {
  return (
    <>
      <Head>
        <title>Quiniela mundial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Header userName = 'Jorge Burguera'/>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenidos a <div className="titleFeatured">Quiniela Mundial</div>
        </h1>
      </main>

      <style jsx>{`
        .titleFeatured {
          color: rgb(255, 153, 0);
          line-height: 1.15;
          font-size: 4rem;
        }
      `}</style>

      <footer className={styles.footer}>
        <div>
          Desarrollador por: Jorge Burguera y Raul Febres - {new Date().getFullYear()}
        </div>
      </footer>
    </>
  )
}


